#!/bin/bash -l

#$ -P noc-lab           # project name
#$ -N i_raven_gen    	# job name

#$ -l h_rt=24:00:00     # hard time limit of 24 hours

#$ -m ea                # send email when finished or aborted

#$ -l mem_per_core=6G	# memory requirements per CPU core
#$ -l gpus=2			# number of GPUs
#$ -l gpu_c=6			# GPU minimum capability

module load miniconda
conda activate i_raven_venv
python main.py --num-samples 10000 --save-dir '../i_raven_data_full/'